#!/usr/bin/env node

var http = require("http");
var proxy = require("request");

var server = http.createServer(function(request, response) {
    console.log(request.url);
    var url = "https://www.google.com.hk" + request.url;
    request.pipe(proxy(url)).pipe(response);
});

server.listen(8000);
console.log("google proxy server is listening");

